apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cloudshop-secure
spec:
  selector:
    app: payment-service
  ports:
    - port: 3004
      targetPort: 80
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: cloudshop-secure
spec:
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
