apiVersion: v1
kind: Pod
metadata:
  name: network-debug
  namespace: cloudshop
spec:
  containers:
    - name: network-debug
      image: nicolaka/netshoot
      command: ['sleep', '3600']


---

apiVersion: v1
kind: Pod
metadata:
  name: network-debug
  namespace: cloudshop-secure
spec:
  containers:
    - name: network-debug
      image: nicolaka/netshoot
      command: ['sleep', '3600']


---

apiVersion: v1
kind: Pod
metadata:
  name: unauthorized-pod
  namespace: cloudshop
spec:
  containers:
    - name: network-debug
      image: nicolaka/netshoot
      command: ['sleep', '3600']

---

apiVersion: v1
kind: Pod
metadata:
  name: traffic-monitor
  namespace: cloudshop
  labels:
    app: traffic-monitor

spec:
  containers:
    - name: traffic-monitor
      image: nicolaka/netshoot
      command: ["sleep", "36000"]
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW




