apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cloudshop-secure
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
      tier: secure
  template:
    metadata:
      labels:
        app: payment-service
        tier: secure
    spec:
      containers:
        - name: apache
          image: httpd:alpine

          ports:
            - containerPort: 3004

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: cloudshop-secure
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      tier: data
  template:
    metadata:
      labels:
        app: database
        tier: data
    spec:
      containers:
        - name: postgre
          image: postgres:13-alpine

          env:
            - name: POSTGRES_DB
              value: cloudshop
            - name: POSTGRES_USER
              value: shopuser
            - name: POSTGRES_PASSWORD
              value: secretpassword


          ports:
            - containerPort: 5432

