apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 10Gi               
  volumeMode: Filesystem
  storageClassName: ""
  hostPath:
    path: /mnt/data
  accessModes:
    - ReadWriteOnce             
  persistentVolumeReclaimPolicy: Retain 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" 
  resources:
    requests:
      storage: 5Gi              

