apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitor
  namespace: monitoring
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: backend-service 

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s

